{
 "title": "RadioBrowser",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header\">\n  <span>stats.API.radio-browser.info</span>\n</div>\n\n"
   }
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Stations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(radio_browser_stations_working) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "radio_browser_tags_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Languages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "radio_browser_language_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Countries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "radio_browser_country_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Calls / Hour",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(radio_browser_api_calls[10m])*3600) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Station clicks / Hour",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(radio_browser_station_clicks[5m]) * 3600",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests by method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(radio_browser_api_calls[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average response time / hour",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(sum(rate(radio_browser_timer_bucket[5m])) by (le))*3600",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(radio_browser_timer_sum[5m])) by (instance))/(sum(rate(radio_browser_timer_count[5m])) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Responses by status code / hour",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(radio_browser_api_calls[5m])*3600) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(radio_browser_cache_hits[5m])/(rate(radio_browser_cache_hits[5m])+rate(radio_browser_cache_misses[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cache hits / hour",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(radio_browser_cache_hits[5m])*3600",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}